# Generated by Django 3.2 on 2021-04-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0006_auto_20210421_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pro',
            field=models.BooleanField(default=False),
        ),
    ]
