# Generated by Django 3.2 on 2021-04-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('postcode', models.CharField(max_length=50)),
                ('short_description', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=50)),
                ('listing_id', models.CharField(max_length=50)),
            ],
        ),
    ]
