# Generated by Django 3.2 on 2021-04-14 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saved_properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedproperty',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='saved_properties', to='jwt_auth.user'),
            preserve_default=False,
        ),
    ]
