# Generated by Django 3.2 on 2021-04-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saved_properties', '0005_merge_0003_auto_20210416_2047_0004_auto_20210417_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedproperty',
            name='address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='savedproperty',
            name='image',
            field=models.CharField(blank=True, max_length=99999),
        ),
        migrations.AlterField(
            model_name='savedproperty',
            name='listing_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='savedproperty',
            name='postcode',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='savedproperty',
            name='property_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='savedproperty',
            name='short_description',
            field=models.CharField(blank=True, max_length=99999),
        ),
    ]
