# Generated by Django 3.2 on 2021-04-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saved_properties', '0006_auto_20210417_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedproperty',
            name='yield_percentage',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
    ]
