# Generated by Django 3.2 on 2021-04-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saved_properties', '0007_savedproperty_yield_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedproperty',
            name='yield_percentage',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
