# Generated by Django 3.2 on 2021-04-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saved_properties', '0008_alter_savedproperty_yield_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedproperty',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
