# Generated by Django 3.2 on 2021-04-22 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saved_properties', '0009_savedproperty_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedproperty',
            name='paid',
        ),
    ]
