# Generated by Django 3.2 on 2021-04-19 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saved_properties', '0006_auto_20210417_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('saved_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yield_calculations', to='saved_properties.savedproperty')),
            ],
        ),
    ]
