# Generated by Django 3.2 on 2021-04-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yield_calculations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yield',
            name='text',
        ),
        migrations.AddField(
            model_name='yield',
            name='annualMaintenance',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yield',
            name='deposit',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yield',
            name='loanTerms',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yield',
            name='managementFee',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yield',
            name='monthlyRent',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yield',
            name='mortgageInterest',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yield',
            name='purchaseCosts',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yield',
            name='purchasePrice',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yield',
            name='refurb',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
